[package]
name = "homework-template"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Ojas Bhagavath <https://ojasb.xyz>"]
license = "GPLv3.0"
description = "This is a Typst template that I use for submitting my assignments/homeworks"
repository = "https://typst.app/universe/package/adaptable-pset/"
keywords = ["problem set", "assignment", "homework"]
categories = ["report"]
# compiler = ""
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
